name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v5.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 90
        days-before-close: 5
        stale-issue-message: 'This issue is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
        stale-issue-label: 'no-issue-activity'
        exempt-issue-label: 'awaiting-approval'
        stale-pr-message: 'This pull request is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
        stale-pr-label: 'no-pr-activity'
        exempt-pr-label: 'awaiting-approval'
        close-issue-reason: not_planned
        
