name: Run Unity IL2CPP UnitTest

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

env:
  BUILD_CONFIG: Debug

jobs:
  unity:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - run: dotnet build -c ${{ env.BUILD_CONFIG }} # require dotnet build (Debug) before Unity build.

    # Run UnitTest
    - uses: actions/cache@v4
      with:
        path: src/MessagePack.UnityClient/Library
        key: Library-MessagePack-StandaloneLinux64
        restore-keys: |
          Library-MessagePack-
          Library-
    - name: Build project
      uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath: src/MessagePack.UnityClient
        unityVersion: 2022.3.12f1
        targetPlatform: StandaloneLinux64
        buildMethod: UnitTestBuilder.BuildUnitTest
        versioning: None
        customParameters: "/headless /ScriptBackend IL2CPP"
    - name: Check UnitTest file is generated
      run: ls -lR ./src/MessagePack.UnityClient/bin/UnitTest
    - name: Execute UnitTest
      run: ./src/MessagePack.UnityClient/bin/UnitTest/StandaloneLinux64_IL2CPP/test

    - uses: Cysharp/Actions/.github/actions/check-metas@main # check meta files
      with:
        directory: src/MessagePack.UnityClient